// D:\weather-react\src\utils\randomCities.js

const cities = [
  'Tokyo',
  'Delhi',
  'Shanghai',
  'Sao Paulo',
  'Mumbai',
  'Mexico City',
  'Beijing',
  'Osaka',
  'Cairo',
  'New York',
  'Dhaka',
  'Karachi',
  'Buenos Aires',
  'Kolkata',
  'Istanbul',
  'Chongqing',
  'Lagos',
  'Manila',
  'Rio de Janeiro',
  'Tianjin',
  'Kinshasa',
  'Guangzhou',
  'Los Angeles',
  'Moscow',
  'Shenzhen',
  'Lahore',
  'Bangalore',
  'Paris',
  'Bogota',
  'Jakarta',
  'Chennai',
  'Lima',
  'Bangkok',
  'Seoul',
  'Nagoya',
  'Hyderabad',
  'London',
  'Tehran',
  'Chicago',
  'Chengdu',
  'Nanjing',
  'Wuhan',
  'Ho Chi Minh City',
  'Luanda',
  'Ahmedabad',
  'Kuala Lumpur',
  'Hong Kong',
  'Riyadh',
  'Baghdad',
  'Santiago',
  'Singapore',
  'Madrid',
  'Toronto',
  'Sydney',
];

export const getRandomCity = () => {
  const randomIndex = Math.floor(Math.random() * cities.length);
  return cities[randomIndex];
};
